target-bpf-obj := int-sink2+filter.bpf.o

int-sink+filter-bpf-objs := int-sink.bpf.o filter-export.bpf.o

int-sink2+filter-bpf-objs := int-sink2.bpf.o

collector+filter-bpf-objs:= collector.bpf.o filter-export.bpf.o