target-bpf-obj := int-sink+filter.bpf.o collector+filter.bpf.o int-sink+filter+debug.bpf.o

int-sink+filter-bpf-objs := int-sink.bpf.o filter-export.bpf.o

int-sink+filter+debug-bpf-objs := int-sink.bpf.o filter-export.bpf.o debug.bpf.o

collector+filter-bpf-objs:= collector.bpf.o filter-export.bpf.o